language: java
cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

install:
  - gradle clean

script:
  - gradle build

after_failure:
  - cat file:///home/travis/build/kkojaeh/pico-erp-facility/facility-test/build/reports/tests/test/index.html
