language: java
cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

install:
  - ./gradlew clean

script:
  - ./gradlew build

after_script:
  - echo $TRAVIS_TEST_RESULT
